# Generated by Django 4.0.4 on 2022-05-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='author_user_id',
        ),
    ]
