# Generated by Django 4.0.4 on 2022-05-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_author_comment_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user',
            new_name='author',
        ),
    ]
