# Generated by Django 4.0.4 on 2022-05-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_author_user_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
    ]
